### ISSUE TITLE
Enable collection of metrics and logs from tmpnet networks in CI

### ISSUE THREAD

**Issue by maru-ava** [ava-labs/hypersdk#1909]
To enable collection of metrics and logs in CI for tmpnet networks:

- Use the `run-monitored-tmpnet-cmd` action as per the example of [subnet-evm](https://github.com/ava-labs/subnet-evm/blob/master/.github/workflows/tests.yml#L150) (note though that some of the params have changed in recent avalanchego: prometheus_id -> prometheus_username and loki_id -> loki_username)

```
      - name: Run Warp E2E Tests
        uses: ava-labs/avalanchego/.github/actions/run-monitored-tmpnet-cmd@v1.11.13
        with:
          run: AVALANCHEGO_BUILD_PATH=/tmp/e2e-test/avalanchego ./scripts/run_ginkgo_warp.sh
          prometheus_id: ${{ secrets.PROMETHEUS_ID || '' }}
          prometheus_password: ${{ secrets.PROMETHEUS_PASSWORD || '' }}
          loki_id: ${{ secrets.LOKI_ID || '' }}
          loki_password: ${{ secrets.LOKI_PASSWORD || '' }}
```

 - Create the referenced secrets
 - Copy the required scripts from avalanchego to the scripts/ directory of the hypersdk repo
   - [./scripts/run_prometheus.sh](https://github.com/ava-labs/avalanchego/blob/master/scripts/run_prometheus.sh)
   - [./scripts/run_promtail.sh](https://github.com/ava-labs/avalanchego/blob/master/scripts/run_promtail.sh)
